In [79]:
# from
# http://iamtrask.github.io/2015/07/12/basic-python-network/
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [80]:
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [81]:
# output dataset            
y = np.array([[0,0,1,1]]).T
y

array([[0],
       [0],
       [1],
       [1]])

In [82]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

In [83]:
# initialize weights randomly with mean 0
wts = 2 * np.random.random((3,1)) - 1

for iter in xrange(100):

    # forward propagation
    X_dot_wts = np.dot(X, wts)
    sigmoid = nonlin(X_dot_wts)
    
    # how much did we miss?
    sigmoid_error = y - sigmoid

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    sigmoid_gradient = nonlin(sigmoid, True)
    sigmoid_delta = sigmoid_error * sigmoid_gradient

    # update weights
    wts += np.dot(X.T,sigmoid_delta)
    print 'iter number %s' % (iter + 1)
    print 'input weights\n%s' % wts
    print 'X dot weights\n%s' % X_dot_wts
    print 'predicted y is\n%s' % sigmoid
    print 'error is\n%s ' % sigmoid_error
    print 'l1_delta is\n%s' % sigmoid_delta
    print 'updated weights are\n%s' % wts
    print 30*"*"
print "Output After Training:"
print l1

iter number 1
input weights
[[ 0.12025406]
 [ 0.50456196]
 [-0.85063774]]
X dot weights
[[-0.99977125]
 [-0.55912226]
 [-1.16572724]
 [-0.72507825]]
predicted y is
[[ 0.2689864 ]
 [ 0.36375058]
 [ 0.23762817]
 [ 0.3262757 ]]
error is
[[-0.2689864 ]
 [-0.36375058]
 [ 0.76237183]
 [ 0.6737243 ]] 
l1_delta is
[[-0.05289153]
 [-0.08418501]
 [ 0.13811206]
 [ 0.14809799]]
updated weights are
[[ 0.12025406]
 [ 0.50456196]
 [-0.85063774]]
******************************
iter number 2
input weights
[[ 0.40563039]
 [ 0.54131537]
 [-0.72857311]]
X dot weights
[[-0.85063774]
 [-0.34607578]
 [-0.73038368]
 [-0.22582172]]
predicted y is
[[ 0.29929909]
 [ 0.41433436]
 [ 0.32511054]
 [ 0.44378327]]
error is
[[-0.29929909]
 [-0.41433436]
 [ 0.67488946]
 [ 0.55621673]] 
l1_delta is
[[-0.06276875]
 [-0.10054295]
 [ 0.14807998]
 [ 0.13729636]]
updated weights are
[[ 0.40563039]
 [ 0.54131537]
 [-0.72857311]]
******************************
iter number 3
input weights
[[ 0.65701265]
 [ 0.53906065]
 [-0.66099